# Generated by Django 2.2.4 on 2021-07-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
